# Generated by Django 5.2.18 on 2026-10-07 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('finance', '0001_initial'),
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='beneficiaries.business'),
        ),
        migrations.AddField(
            model_name='equityrecord',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equity_records', to='beneficiaries.business'),
        ),
        migrations.AddField(
            model_name='equityrecord',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equity_records', to='hubs.hub'),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funding_sources', to='beneficiaries.business'),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funding_sources', to='hubs.hub'),
        ),
        migrations.AddField(
            model_name='liability',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='liabilities', to='beneficiaries.business'),
        ),
        migrations.AddField(
            model_name='projection',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projections', to='beneficiaries.business'),
        ),
        migrations.AddField(
            model_name='projection',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projections', to='hubs.hub'),
        ),
        migrations.AddField(
            model_name='revenuestream',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_streams', to='hubs.hub'),
        ),
        migrations.AddField(
            model_name='startupcost',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='startup_costs', to='beneficiaries.business'),
        ),
        migrations.AddField(
            model_name='startupcost',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='startup_costs', to='hubs.hub'),
        ),
    ]
