# Generated by Django 5.2.18 on 2026-10-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedspreadsheetimport',
            name='report_only',
            field=models.BooleanField(default=False),
        ),
    ]
