# Generated by Django 5.2.18 on 2026-10-07 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=24)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('view_all_hubs', 'Can view data for all hubs')],
            },
        ),
        migrations.CreateModel(
            name='HubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hubs.hub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hub__name', 'user__last_name'],
                'constraints': [models.UniqueConstraint(fields=('hub', 'user'), name='unique_hub_membership')],
            },
        ),
    ]
