# Generated by Django 5.2.18 on 2026-10-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hub',
            options={'ordering': ['name']},
        ),
    ]
