# Generated by Django 5.2.18 on 2026-10-07 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0001_initial'),
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='direction',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], default='IN', max_length=3),
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='hubs.hub')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='products.product')),
            ],
            options={
                'ordering': ['hub__name', 'product__name'],
                'constraints': [models.UniqueConstraint(fields=('hub', 'product'), name='unique_hub_product_stock'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventory_balance_nonnegative')],
            },
        ),
    ]
