# Generated by Django 5.2.18 on 2026-10-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
        ('hubs', '0002_alter_hub_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryprofile',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiaries', to='hubs.hub'),
        ),
        migrations.AddField(
            model_name='business',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='hubs.hub'),
        ),
    ]
